apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - args:
            - --config-path
            - /etc/envoy/envoy.yaml
            - --bootstrap-version
            - "3"
            - --service-node
            - ingress-envoy
            - --service-cluster
            - ingress-envoy
          image: envoyproxy/envoy:v1.18-latest
          name: envoy
          ports:
            - name: http
              containerPort: 10000
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 256Mi
          volumeMounts:
            - mountPath: /etc/envoy
              name: envoy
      volumes:
        - name: envoy
          configMap:
            name: envoy
