name: envoy

on:
  pull_request:
    paths:
      - .github/workflows/envoy.yaml
      - envoy_dynamic/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/envoy.yaml
      - envoy_dynamic/**

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: make validate
